### ISSUE TITLE
Converting pbf to typescript - Both the compiler and the output.

### ISSUE THREAD

**Issue by vicb** [mapbox/pbf#122]
I am interested in #107 that adds support for generating es6/typescript.

Also it seems like this repository would benefit from updates.

I would love to see the following happen:
1) Convert the current pbf code to Typescript (same functionality),
2) Update the compiler to generate Typescript code ONLY,
3) Call the Typescript compiler programmatically to convert to ES6, common-js, ...

What do you think ? 

/cc @mourner

**Comment by til-schneider** [comment]
> 1. Convert the current pbf code to Typescript (same functionality)

This would certainly be a good idea.

> 2. Update the compiler to generate Typescript code ONLY,
> 3. Call the Typescript compiler programmatically to convert to ES6, common-js, ...

I don't think this is really necessary. In [my pull request](https://github.com/mapbox/pbf/pull/107) it only needs a few if statements around the parts which would add the type information into the generated code.

I would propose to keep it this way for the following reasons:
- faster at runtime
- less complexity as having to generate a temp file which is transpiled by TypeScript afterwards
- less runtime dependencies (since TypeScript would only be a dev dependency)

**Comment by mourner** [comment]
> 1. Convert the current pbf code to Typescript (same functionality)

Sorry but definitely not.

> I am interested in #107 that adds support for generating es6/typescript.

Definitely planning on bringing that in though — let's keep the discussion there.
