### ISSUE TITLE
pbf is rounding the Long integer value to nearest value why?

### ISSUE THREAD

**Issue by syamasundararao** [mapbox/pbf#126]
While using VectorGrid Pbf I have faced an issue of rounding of 20 digit number to nearest value 
actual value : 2216087363469098752
output value:2216087363469098800 

Why I need actual value ..

**Comment by mourner** [comment]
Because JavaScript stores numbers as 64-bit floating point and can't precisely represent values bigger than `Number.MAX_SAFE_INTEGER`, which is 9007199254740991. There's a potential solution for this explored in #115.

**Comment by kjvalencik** [comment]
@syamasundararao In addition to what @mourner said, this library focuses on _performance_ and being unable to accurately represent 64-bit integers is an intentional tradeoff for performance since, until recently, JavaScript did not have native support. This is a reasonable tradeoff because 53-bit integers is sufficient for many use cases.

It's natively supported now, but the performance characteristics have not been deeply explored and progress is being tracked in https://github.com/mapbox/pbf/pull/115.
